title: <p align="center"> Segio Ortiz Rios</p>

logo: /assets/img/mi_logo.png

description: <p align="center">ğŸ—ï¸ Structural Engineering </p>
  <p align="center">
  <a href="www.linkedin.com/in/sergioortizrmx/">LinkedIn</a>
  </p>
  
  <p align="justify">
  Profesional egresado de la carrera de IngenierÃ­a Civil del TecnolÃ³gico Nacional de MÃ©xico, Campus Zacatepec.
  <br><br>
  DiseÃ±ador estructural
  <br><br>
  </p>

google_analytics: G-ZZYG0XLBM7 
theme: jekyll-theme-minimal
